import time
print("ARKMOON - SURVIVAL IS STARTING...")
time.sleep(2)
print("GAME START")
time.sleep(2)
print("It is the year 3099. You are on a solo mission to restock the base on the moon with soil and seeds to grow more plants.")
time.sleep(2)
print("You have just landed but you are in trouble. You have landed 300 kilometers from the moon base!")
time.sleep(2)
print("You can get to the base in 3 days on your lunar rover")
time.sleep(2)
print("The lunar rover can only fit you in your spacesuit and 4 other items")
time.sleep(2)
print("Out of the items below, which do you bring?")
time.sleep(2)
print("A: 3 liters of water")
time.sleep(2)
print("B: Shampoo")
time.sleep(2)
print("C: An extra spacesuit")
time.sleep(2)
print("D: A shovel")
time.sleep(2)
print("E: A 10 day oxygen supply")
time.sleep(2)
print("F: Solar panels")
time.sleep(2)
print("G: The seeds for your mission")
time.sleep(2)
print("H: The soil for your mission")
time.sleep(2)
print("I: A 3 day food supply")
time.sleep(2)
choice = input("Type the letter of the 4 items you would like to bring, not seperated, in alphabetical order, in all capitals. Do NOT add spaces Ex: ABCD - ")
time.sleep(2)
print("PROCESSING...")
time.sleep(2)
if choice != "AEFI":
    print("You have died. You did not choose the correct items to survive.")
    time.sleep(.75)
    print("ARKMOON - SURVIVAL, GAME OVER - YOU LOSE")
if choice == "AEFI":
    print("You win. You have chosen the correct items to survive.")
    time.sleep(.75)
    print("ARKMOON - SURVIVAL, GAME OVER - YOU WIN")